# Generated by Django 4.2.2 on 2023-08-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'permissions': [('can_generate_certificate', 'Can generate certificate'), ('can_view_generated_certificate', 'Can view generated certificate')]},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
