# Generated by Django 4.2.4 on 2024-08-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate_app", "0002_alter_certificate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="position",
            field=models.CharField(default="Intern", max_length=255),
        ),
    ]
